name: build authoritive docker images

on:
  push:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        backend: ["bind", "ldap", "lua2", "mariadb", "mysql", "odbc", "pgsql", "pipe", "random", "remote", "sqlite3"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: powerdns
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ghcr.io/${{ github.actor }}/powerdns:${{ matrix.backend }}
          build-args: |
            BACKEND=${{ matrix.backend }}
